### ISSUE TITLE
如何得到中间输出？

### ISSUE THREAD

**Issue by zhyj3038** [PaulChongPeng/YOLO2TensorFlow#2]
您好，十分感谢您的工作！ 我有一个问题，使用slim是否仅仅可以得到最后的loss， 我希望可以得到中间的loss打印出来，并且得到中间的一些xywh等，是不是没法子做到？

**Comment by TaihuLight** [comment]
I also want to known how to get the output vector/tensor value of last layer in yolo2

**Comment by PaulChongPeng** [comment]
You can get any value you want by adding summary.
I have added some loss,you can easily check it in tensorboard.

        summaries.add(tf.summary.scalar('loss_total', total_loss))
        summaries.add(tf.summary.scalar('loss_confidence', confidence_loss))
        summaries.add(tf.summary.scalar('loss_confidence_object', objects_loss))
        summaries.add(tf.summary.scalar('loss_confidence_no_object', no_objects_loss))
        summaries.add(tf.summary.scalar('loss_coordinate', coordinate_loss))
        summaries.add(tf.summary.scalar('loss_coordinate_xy', xy_loss))
        summaries.add(tf.summary.scalar('loss_coordinate_wh', wh_loss))
